version: "3"
services:
  mysql:
    image: mysql:5.7.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: totallyunsafe
    volumes:
      - ./backend/infrastructure/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "2000:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: totallyunsafe
  apache:
    build: ./backend/docker/apache
    container_name: apache
    depends_on:
      - mysql
    volumes:
      - ./backend/source:/var/www/html/api
      - ./frontend/src:/var/www/html/
    ports:
      - "8080:80"
